# Generated by Django 5.1.6 on 2025-02-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='1234', max_length=15, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
